Remove python installation as part of Linux uninstall process, Added Gnome and wget for Linux installation and .bashrc file change.
ansys/python-installer-qt-gui pull request #245
Opened 2024-03-20 14:11 UTC by anssakthi

Pull request for the implementation of removal of python installation as part of Linux uninstall process, Added Genome and wget for Linux installation and .bashrc file change. 

## Description
This Pull request has following features,

1.  As part Linux uninstallation process user can remove python binaries.
2.  Added Ansys-python-Manager launch command to .bashrc file.
3.  Added Gnome and wget as one of the dependencies in the installation process to support wsl. 
4.  Added pre-compiled python version NOTE/Warning on the installer

## Related Issue
https://github.com/ansys/python-installer-qt-gui/issues/238
https://github.com/ansys/python-installer-qt-gui/issues/241

2024-03-20 14:49 UTC, RobPasMue requested changes

2024-03-20 14:49 UTC, RobPasMue commented on doc/source/installer.rst
> +           * If you want to remove all python installations which was installed by
```suggestion
           * If you want to remove all Python installations which were installed by
```

2024-03-20 14:49 UTC, RobPasMue commented on doc/source/installer.rst
> +             ``Delete python installations`` checkbox
```suggestion
             ``Delete Python installations`` checkbox
```

2024-03-20 14:49 UTC, RobPasMue commented on doc/source/installer.rst
> +             ``Delete python installations`` checkbox
```suggestion
             ``Delete Python installations`` checkbox
```

2024-03-20 14:49 UTC, RobPasMue commented on doc/source/installer.rst
> +        #. Restart the machine and run ``ansys_python_installer``.
```suggestion
        #. Restart the machine and run ``ansys_python_manager``.
```

2024-03-20 14:49 UTC, RobPasMue commented on src/ansys/tools/installer/constants.py
> +NOTE - Only 'Python 3.11' version is readily available. Other python versions are compiled from source and it takes approx 2-3 minutes."""
```suggestion
NOTE - Only 'Python 3.11' version is readily available. Other Python versions are compiled from source and it takes approximately 2-3 minutes."""
```

2024-03-20 14:49 UTC, RobPasMue commented on src/ansys/tools/installer/linux_functions.py
> +    ansys_manager_installed_only : Boolean(default: False)
```suggestion
    ansys_manager_installed_only : bool, optional
```

2024-03-20 14:49 UTC, RobPasMue commented on src/ansys/tools/installer/uninstall.py
> +                "Delete python installations"
```suggestion
                "Delete Python installations"
```

2024-03-21 06:44 UTC, anssakthi commented on src/ansys/tools/installer/uninstall.py
>          if self.uninstall_window_cache_remove_venv_checkbox.isChecked():
Nice catch @RobPasMue we forgot to include this in uninstaller script. Thanks

2024-03-27 10:57 UTC, RobPasMue commented on src/ansys/tools/installer/installed_table.py
> +        delete_action = menu.addAction("Delete virtual environments")
```suggestion
        delete_action = menu.addAction("Delete virtual environment")
```

2024-03-27 10:58 UTC, RobPasMue approved these changes

2024-03-27 10:58 UTC, RobPasMue commented on src/ansys/tools/installer/main.py
> +            python_version_warning.setStyleSheet("color: red;")
```suggestion
```

I would not add color to the note.

2024-03-27 10:59 UTC, RobPasMue commented
All good - this PR can be merged once CI/CD passes

2024-04-01 05:55 UTC, merged